import { StyleSheet } from "react-native";

// [인증 화면 공통 스타일] 로그인/아이디 찾기/비밀번호 찾기 디자인을 통일하기 위한 공유 스타일
export const authStyles = StyleSheet.create({
  safe: { flex: 1, overflow: "hidden" },
  backRow: { paddingHorizontal: 20, paddingTop: 8 },
  backText: { fontSize: 13, fontWeight: "600" },
  content: { flexGrow: 1, justifyContent: "center", padding: 24, gap: 20 },
  hero: { alignItems: "center", paddingVertical: 16 },
  logo: { width: 64, height: 64, borderRadius: 18, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  logoText: { color: "white", fontWeight: "700", fontSize: 28 },
  logoSmall: { width: 48, height: 48, borderRadius: 14, alignItems: "center", justifyContent: "center", marginBottom: 10 },
  logoTextSmall: { color: "white", fontWeight: "700", fontSize: 20 },
  brandText: { fontSize: 24, fontWeight: "800", letterSpacing: -0.5 },
  tagline: { fontSize: 13, marginTop: 6, textAlign: "center" },
  card: { borderWidth: 1, borderRadius: 16, padding: 18, gap: 10 },
  input: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14 },
  pillButton: { borderRadius: 999, borderWidth: 1.2, paddingHorizontal: 16, paddingVertical: 9 },
  pillButtonText: { fontWeight: "700", fontSize: 12 },
  bigPillButton: { borderRadius: 999, paddingVertical: 16, alignItems: "center", marginTop: 10 },
  inlineRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  inlineInput: { flex: 1 },
  submit: { borderRadius: 12, paddingVertical: 15, alignItems: "center", marginTop: 4 },
  linkRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  linkText: { fontSize: 12, fontWeight: "600" },
  linkDivider: { fontSize: 12 },
  resultBlock: { alignItems: "center", gap: 4, paddingVertical: 6 },
  resultValue: { fontSize: 19, fontWeight: "800", marginTop: 2 },
  divider: { height: 1, marginVertical: 8 },
  checkRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 5 },
  checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 1.4, alignItems: "center", justifyContent: "center" },
  checkboxMark: { fontSize: 12, fontWeight: "800" },
  checkLabel: { flex: 1, fontSize: 12, fontWeight: "600" },
  checkRequiredTag: { fontSize: 10 },
});
